name: netru_app
description: A new Flutter project with Clean Architecture
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  animate_do: ^4.2.0
  animator:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  easy_localization:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^8.1.4
  flutter_launcher_icons: ^0.14.4
  flutter_map: ^8.2.1
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  geolocator: ^14.0.2
  get_it: ^8.2.0
  google_fonts: ^6.3.0
  http: ^1.5.0
  intl:
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  location: ^8.0.1
  lottie: ^3.3.1
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  change_app_package_name: ^1.5.0
  # Supabase dependencies
  supabase_flutter: ^2.8.1
  # Google Sign-In dependency (used in auth flows)
  google_sign_in: ^6.2.1
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.1.2
  image: ^4.2.0
  path_provider: ^2.1.4
  # Document scanner with automatic cropping
  cunning_document_scanner: ^1.3.1
  # Additional utilities for file handling
  mime: ^1.0.6
  path: ^1.9.0
  # Additional dependencies for logging and utilities
  logger: ^2.4.0
  uuid: ^4.5.1
  # Additional packages for enhanced mobile login & signup
  pin_code_fields: ^8.0.1  # For OTP input
  flutter_otp_text_field: ^1.1.3  # Alternative OTP widget
  country_picker: ^2.0.24  # Country code picker for phone
  phone_number: ^2.1.0  # Phone number validation
  flutter_image_compress: ^2.4.0 # Image compression (replacement for flutter_native_image)
  image_cropper: ^8.0.2  # Image cropping for documents

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/translations/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai-Light.ttf

# إعدادات تخصيص أيقونة التطبيق
flutter_native_splash:
  android: false
  ios: false
# logoapp.png


flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logoapp.png"
  min_sdk_android: 21 # android min sdk min:16, default 21